(defun get-compile-command (prefix)
  (if (= prefix 1)
      (concat "g++ " (buffer-name) " -std=c++0x -DLOKALNO -Wno-unused-result -O2 -Wall -o " (file-name-sans-extension (buffer-name)))
  )
)

(defun save-and-quick-compile (prefix) (interactive "p")
  (save-buffer 0)
  (compile (get-compile-command prefix))
)

(defun zuza-quick-run () (interactive)
  (if (file-readable-p "makefile")
      (async-shell-command (concat "make run " make-run-command) )
      (async-shell-command (concat "./" (file-name-sans-extension (buffer-name))))
      )
)

(defun zuza-tc-run-0 () (interactive)
  (async-shell-command (concat "./" (file-name-sans-extension (buffer-name)) " 0"))
)
(defun zuza-tc-run-1 () (interactive)
  (async-shell-command (concat "./" (file-name-sans-extension (buffer-name)) " 1"))
)
(defun zuza-tc-run-2 () (interactive)
  (async-shell-command (concat "./" (file-name-sans-extension (buffer-name)) " 2"))
)
(defun zuza-tc-run-3 () (interactive)
  (async-shell-command (concat "./" (file-name-sans-extension (buffer-name)) " 3"))
)
(defun zuza-tc-run-4 () (interactive)
  (async-shell-command (concat "./" (file-name-sans-extension (buffer-name)) " 4"))
)
(defun zuza-tc-run-5 () (interactive)
  (async-shell-command (concat "./" (file-name-sans-extension (buffer-name)) " 5"))
)
(defun zuza-tc-run-6 () (interactive)
  (async-shell-command (concat "./" (file-name-sans-extension (buffer-name)) " 6"))
)
