(spacemacs/set-leader-keys-for-major-mode 'c++-mode "c" 'save-and-quick-compile)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "r" 'zuza-quick-run)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "n" 'next-error)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "p" 'previous-error)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "t 0" 'zuza-tc-run-0)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "t 1" 'zuza-tc-run-1)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "t 2" 'zuza-tc-run-2)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "t 3" 'zuza-tc-run-3)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "t 4" 'zuza-tc-run-4)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "t 5" 'zuza-tc-run-5)
(spacemacs/set-leader-keys-for-major-mode 'c++-mode "t 6" 'zuza-tc-run-6)
